language: cpp

os:
  - linux
  - osx
  
sudo: required

compiler:
  - clang++
  - g++

matrix:
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: g++

env:
  global:
    - "FTP_USER=bnsmith"

before_install:
  - chmod +x scripts/*.sh
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then 
# g++4.8.1
if [ "$1" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

# clang 3.4
if [ "$1" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
sudo apt-get install freeglut3-dev libglew-dev libfreetype6-dev libopenal-dev sshpass
#only install doxygen if we're on g++, save time on clang
if [ "$1" == "g++" ]; then sudo apt-get install doxygen; fi
sudo apt-get update -qq

#g++4.8.1
if [ "$1" == "g++" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
if [ "$1" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi

# clang 3.4
if [ "$1" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
if [ "$1" == "clang++" ]; then export CXX="clang++-3.4"; fi
  ;fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then . ./scripts/travis_setup_mac.sh; fi

before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make source_parsing && make engine_mac && make editor_mac && make testing_mac && make assets_mac; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make source_parsing && make engine && make editor && make testing && make assets; fi
  - if [ "$CXX" == "g++" ]; then make docs; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./scripts/travis_deploy.sh
