language: cpp

compiler:
  - clang++
  - g++

env:
  global:
    - "FTP_USER=bnsmith"

before_install:
  - chmod +x scripts/*.sh
  - . sudo ./scripts/travis_setup.sh

before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - make engine && make editor && make testing && ./build/my-engine-test && make docs

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./scripts/travis_deploy.sh
