language: cpp

os:
  - linux
  - osx

compiler:
  - clang++
  - g++

matrix:
  allow_failures:
    - os: osx
  exclude:
    - os: osx
      compiler: g++

env:
  global:
    - "FTP_USER=bnsmith"

before_install:
  - chmod +x scripts/*.sh
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ./scripts/travis_setup_linux.sh $CXX;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then . ./scripts/travis_setup_mac.sh; fi

before_script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make engine_mac && make editor_mac && make testing_mac; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make engine && make editor && make testing; fi
  - if [ "$CXX" == "g++" ]; then make docs; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./scripts/travis_deploy.sh
